"""Assemble three Plotly figures into a single self-contained HTML page."""
from __future__ import annotations

import pandas as pd
import plotly.graph_objects as go

DIV_IDS: tuple[str, ...] = ("fig_scatter_vol", "fig_scatter_beta", "fig_beta_ts")
SECTION_TITLES: tuple[str, ...] = (
    "Risk vs Return",
    "Beta vs Return",
    "Segment β with regime bands",
)
_REQUIRED_FIGURES: int = 3

_CSS = """
:root { color-scheme: light; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  margin: 0;
  background: #fafafa;
  color: #222;
}
.container { max-width: 1200px; margin: 0 auto; padding: 24px; }
header { border-bottom: 1px solid #ddd; margin-bottom: 24px; padding-bottom: 12px; }
header h1 { margin: 0 0 4px; font-size: 24px; }
header .meta { color: #666; font-size: 13px; }
section { background: #fff; border: 1px solid #e6e6e6; border-radius: 8px;
  padding: 16px; margin-bottom: 24px; }
section h2 { margin: 0 0 12px; font-size: 18px; }
footer { color: #888; font-size: 12px; text-align: center; padding: 16px; }
"""


def assemble(
    figures: list[go.Figure],
    *,
    run_date: pd.Timestamp,
    methodology_version: str,
) -> str:
    """Assemble three figures into one self-contained HTML page.

    Args:
        figures: list of exactly three Plotly figures
            (scatter_vol_return, scatter_beta_return, beta_timeseries).
        run_date: report run date for header.
        methodology_version: engine methodology version string.

    Returns:
        Full HTML document string (starts with <!DOCTYPE html>).

    Raises:
        ValueError: if `figures` does not contain exactly 3 entries.
    """
    if len(figures) != _REQUIRED_FIGURES:
        raise ValueError(
            f"assemble requires exactly {_REQUIRED_FIGURES} figures, got {len(figures)}"
        )

    # First fig pulls plotly.js from CDN; subsequent figs reuse it.
    fig_html_blocks: list[str] = []
    for idx, (fig, div_id, title) in enumerate(
        zip(figures, DIV_IDS, SECTION_TITLES, strict=True)
    ):
        include: str | bool = "cdn" if idx == 0 else False
        block = fig.to_html(
            include_plotlyjs=include,
            full_html=False,
            div_id=div_id,
            config={"displaylogo": False},
        )
        fig_html_blocks.append(f'<section><h2>{title}</h2>{block}</section>')

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>RoRo Risk-Regime Report — {run_date.date()}</title>
<style>{_CSS}</style>
</head>
<body>
<div class="container">
<header>
<h1>RoRo Risk-Regime Report</h1>
<div class="meta">Run date: {run_date.date()} &nbsp;|&nbsp;
Methodology: v{methodology_version}</div>
</header>
{''.join(fig_html_blocks)}
<footer>Generated by RoRo · methodology v{methodology_version}</footer>
</div>
</body>
</html>
"""
